language: csharp
solution: OdooDotNet.sln
addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial

env:
  global:
  - VERSION="8.0"

install:
  - createdb test
  - pip install pytz
  - git clone https://github.com/savoirfairelinux/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools -b unhardcode
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - nuget restore OdooDotNet.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - /home/travis/odoo-8.0/openerp-server -d test -i crm,sale --stop-after-init --workers=0 --log-level=warn
  - /home/travis/odoo-8.0/openerp-server -d test --log-level=warn &
  - xbuild /p:Configuration=Release OdooDotNet.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Testing/bin/Release/Testing.dll